### ISSUE TITLE
Cannot connect yangcli to netconfd

### ISSUE THREAD

**Issue by torokati44** [vlvassilev/yuma123#33]
Upon trying to connect from yangcli to netconfd, the messages I get:

From `yangcli`:

> Connect attempt with following parameters:
> input {
>   user attila
>   server localhost
>   password ****
>   ncport 22
>   timeout 30
>   public-key $HOME/.ssh/id_rsa.pub
>   private-key $HOME/.ssh/id_rsa
>   use-agent false
>   transport ssh
>   tcp-direct-enable false
> }
> val->res is NO_ERR.
> 
> yangcli: Starting NETCONF session for attila on localhost
> yangcli: Start session 1 OK for server 'default'
> ses got send request on session 1
> mgr_top: get node failed (xml reader EOF); session dropped

From `netconfd`:

> New session 1 created OK
> agt_connect got node
> agt_connect msg ok
> agt_sys: generating <netconf-session-start> notification
> Session 1 for attila@127.0.0.1 now active (base:1.1)
> ses: session 1 shut by remote peer
> agt_sys: generating <netconf-session-end> notification

What might be going wrong?

**Comment by torokati44** [comment]
I found the `lpenz/openyuma` Docker image on Docker Hub, that worked.

**Comment by vlvassilev** [comment]
Hi,

Sorry for the delay. Seems notifications are not sent when issue is opened. Seems you have correctly configured everything but I wonder what caused the "mgr_top: get node failed (xml reader EOF); session dropped" Can you start yangcli with full debug e.g.

yangcli --server=localhost --log-level=debug4

... also how does your netconfd server command line look like?

The original Yuma clone has some unresolved issues and does not support YANG 1.1 features and some of the modules are outdated. There are quite a lot of issues that are resolved in yuma123. It is worth figuring out what went wrong.

I personally do not use docker but there are some docker related images for yuma123 https://hub.docker.com/u/yuma123/

Vladimir

**Comment by torokati44** [comment]
Thanks, I'm now using the docker images of `yuma123`, like this:

shell1: `$ docker network create yang_net`
shell1: `$ docker run -ti --rm --name netconfd --env NETCONF_USER=admin --env NETCONF_PASSWORD=admin --env NETCONF_PORT=22  --network yang_net  yuma123/netconfd`
shell2: `$ docker run -ti  --network yang_net  yuma123/yangcli --server=netconfd --user=admin --password=admin --ncport=22`

This is enough for me for now, so if you're not insisting on debugging my original issue, we can leave it at that.

**Comment by torokati44** [comment]
My `netconfd` command line is simply - based on the README in the https://github.com/vlvassilev/omnetpp-summit-hackathon-2018 repo:

`$ rm /tmp/ncxserver.sock ; netconfd --log-level=debug4 --port=22`

I had a couple of `--module foobar.yang` arguments in there before, but they don't seem to make a difference regarding the session drop.

The output of `yangcli --server=localhost --log-level=debug4 --ncport=22` is:
https://gist.github.com/torokati44/bc5e94a9040b391f235bbdc6e1280360
I hope there isn't any sensitive information in there... :smile:  - I removed my Unix password... By the way, why does key-based authentication not work?

From this, my guess is that since my `~/.bashrc` / `~/.bash_aliases` has some commands in it that print (`echo`) some information about the aliases every time I open a terminal, these lines might be somehow included into an XML document, which is presumably created by capturing the standard output of a shell script?

**And indeed**, removing those `echo` statements from `~/.bash_aliases` solved the issue.

**Comment by vlvassilev** [comment]
Problem solved. You are using --ncport=22 (the omnetpp-summit-hackathon-2018 README.md uses the default=830) which opens the  sshd subsystem for port 22 and not the netconf subsystem configured for listening on port 830 (if your sshd server configuration is as recommended). This is why your port 22 connection calls your ~/.bash_aliases script.

As for the keys you have to tell me what command does not work. I use the following:
yangcli --user=$USER --server=localhost --ncport=$port --public-key="${HOME}/.ssh/id_rsa.pub" --private-key="${HOME}/.ssh/id_rsa" --password=""

**Comment by torokati44** [comment]
Alright, so it was a user error after all, my bad.

I still got a `(connect failed)` error on my machine, until entering the command mentioned on the top of the `/etc/ssh/sshd_config` file:
```
# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
```
Since then, I can connect on port 830, using my password.
Still not working with keys though, not even with your command, not even if I generate and add a new key (either with or without a passphrase).
```
mgr_ses: Got server authentication methods: publickey,gssapi-keyex,gssapi-with-mic,password

mgr_ses: SSH2 publickey authentication failed:
  libssh2 username/public key invalid
  key file was '/home/attila/new_key_rsa.pub'
```

But it doesn't matter that much, I can already use it on my machine with the password, as well as in Docker, and at this time I only need all of this to edit instance data .xml files, while making sure they remain conformant.

**Comment by vlvassilev** [comment]
SELinux is out of my competence domain. I use Debian. But is good to have this information available!

The keys should also work if you can:
ssh localhost -p 830 -s netconf
.. without password.  Are you sure the public key is added to .ssh/authorized_key.

Thanks for the input!

**Comment by torokati44** [comment]
I already set SELinux to be permissive - effectively disabled it.
My public key is in the `authorized_keys` file.
I can `ssh localhost` just fine, without entering my password, or the passphrase of my key.
I can even `ssh localhost -p 830 -s netconf` without password or passphrase from the same shell, and I get a `<hello> ... </hello>` reply.

Do you think that the `UsePAM yes` setting in `/etc/ssh/sshd_config` can be the culprit?
I wouldn't want to disable it, because there's a warning right next to it:

```
# WARNING: 'UsePAM no' is not supported in Fedora and may cause several
# problems.
UsePAM yes
```

I have this suspicion because the debug output of `sshd` mentions PAM when I try to connect with `yangcli`:
https://gist.github.com/torokati44/a172d2722ed23ed51a1c8cece5df92bc

**Comment by vlvassilev** [comment]
If you get <hello> then your configuration is correct (I also hace UsePAM). What does the yangcli command return?:

yangcli --user=$USER --server=localhost --ncport=830 --public-key="${HOME}/.ssh/id_rsa.pub" --private-key="${HOME}/.ssh/id_rsa" --password=""

**Comment by torokati44** [comment]
I'm already on my way home, I'll post the output tomorrow. :)

**Comment by torokati44** [comment]
The output of that command (well, I also added `--log-level=debug4`, I guess that's okay): https://gist.github.com/torokati44/74b3f59c9106306eed20a8288865a422

The public and private key file names are correct, those are also added to the SSH agent.
This is from the same shell, and on the same running `netconfd` instance that allows me to `ssh attila@localhost -p 830 -s netconf` with no issues.

**Comment by torokati44** [comment]
I simply had to add `--use=agent=true` to the `yangcli` command line, and now it works perfectly.
Thank you!

**Comment by vlvassilev** [comment]
OK. Then for some reason ssh-agent for authentication was required on your system. It takes precedence over the  public and private key path arguments so you still had something that was wrong with the public/private key files used without the agent (could be password protection etc.).

There has to be some cause for the libssh2_userauth_publickey_fromfile call to fail.

> gdb --args yangcli --user=$USER --server=localhost --ncport=830 --log-level=debug4 --public-key="${HOME}/.ssh/id_rsa.pubb" --private-key="${HOME}/.ssh/id_rsa" --password=""
> ...
> (gdb) break ssh2_setup
> (gdb) run
> ...
> 

Then ssh2_setup function in netconf/src/mgr/mgr_ses.c has the complete ssh session logic.

**Comment by torokati44** [comment]
I just assumed that it will try to use the agent by default, and ask for the passphrase using a graphical dialog, like most other programs (`git`, `ssh`, `sshfs`, etc.) do. Nevermind that.

When not using the agent:

`libssh2_userauth_publickey_fromfile` returns  `-19` which is `LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED`
I'm not even sure what 'verification' of a key means? :confused: 

I've created a new key pair that does not have a passphrase (although the results are the same if I'm trying one that has a passphrase).
`sshd` 'accepts' the key upon connection, based on `~/.ssh/authorized_keys`.
Again, using this key, I get the `<hello>` reply when manually connecting using `ssh`. 
I've removed all other keys from the `ssh-agent`, the `~/.ssh` directory, and the `~/.ssh/authorized_keys` file.
I also tried creating the key with different comments, like `attila` and `attila@localhost` - no change. I guess this should not matter at all, but I ran out of ideas.

By the way, I found some similar issues others had before, like: https://stackoverflow.com/questions/33231547/using-libssh2-scp-to-retrieve-a-file-fails-to-authenticate-when-scp-from-cmd-wor
